# config.yaml 파일
access_key: "tAHZ6CxjhuFZZ..."
secret_key: "ITzqz2kn1hsC9..."
DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1462015179935056009/7G_B-ryw67hl64bwQSqnfl..."  # [추가] 웹후크 URL 붙여넣기

LOOP_TIME: 15
AMOUNT_TO_BUY: 100000
TRADE_VALUE: 3000000000

AMOUNT: 1,000,000
